baseURL = "https://someguys.blog/"
languageCode = "en-us"
title = "Some Guys Blog"
theme = "beautifulhugo"

[Params]
  since = 2017
  subtitle = "Yet another tech blog of some guy"
  mainSections = ["posts"]
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
  readingTime = false
  wordCount = false
  useHLJS = true
  socialShare = false
  showRelatedPosts = true
  hideAuthor = true

[params.author]
  name = "Britt Treece"
  github = "abtreece"
  bluesky = "abtreece.bsky.social"
  linkedin = "abtreece"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Talks"
    url = "pages/talks"
    weight = 2
